let invalid_fa12 = "FA12_TRANSFER_MISSING"
let invalid_fa2 = "FA2_TRANSFER_MISSING"
let ticket_creation_failed = "TICKET_CREATION_FAILED"
let failed_to_get_ticket_entrypoint = "FAILED_TO_GET_TICKET_ENTRYPOINT"
let unauthorized_ticketer = "UNAUTHORIZED_TICKETER"
let token_not_found = "TOKEN_NOT_FOUND"