[profile.default]
src = "src"
out = "build"
libs = ["lib"]
solc = "0.8.21"

[fmt]
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
