# withdraw.callback(
#     proxy_address=token.l2_token_address,
#     router_address=token.l1_ticketer_address,
#     amount=amount,
#     ticketer_address_bytes=get_ticketer_params(token.l1_ticketer_address)['address_bytes'],
#     ticket_content_bytes=get_ticketer_params(token.l1_ticketer_address)['content_bytes'],
#     receiver_address=wallet.l1_public_key_hash,
#     withdraw_precompile=bridge.l2_withdraw_precompile_address,
#     private_key=wallet.l2_private_key,
#     rpc_url=bridge.l2_rpc_url,
# )
# return
